services:
- name: mongo
  image: mongo
  bindings:
    - containerPort: 27017
      protocol: http
  env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: example

- name: mongo-express
  image: mongo-express
  bindings:
    - containerPort: 8081
      protocol: http
  env:
    - name: ME_CONFIG_MONGODB_ADMINUSERNAME
      value: root
    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
      value: example

- name: todo-server
  project: server/TodoApp.csproj

- name: todo-client
  dockerFile: "./client/Dockerfile"
  bindings:
    - containerPort: 80
      protocol: http