version: '3.4'

services:
  configserver:
    image: steeltoeoss/configserver
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./src/config
        target: /config
    ports:
      - "8888:8888"
  eurekaserver:
    image: steeltoeoss/eurekaserver
    ports:
      - "8761:8761"
  spring-boot-admin:
     image: slydeveloper/spring-boot-admin
     ports:
       - "8889:1111"
     environment:
       SPRING_BOOT_ADMIN_SECURITY_ENABLED: "false"
     depends_on:
       - eurekaserver
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: steeltoe
      MYSQL_DATABASE: steeltoe
      MYSQL_USER: steeltoe
      MYSQL_PASSWORD: steeltoe
    depends_on:
      - configserver
      - eurekaserver
      - spring-boot-admin
  zipkinserver:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  musicservice:
    image: ${DOCKER_REGISTRY-}musicservice
    build:
      context: ./src/MusicStoreService
      dockerfile: Dockerfile
    depends_on:
      - configserver
      - eurekaserver
      - mysql
  shoppingcartservice:
    image: ${DOCKER_REGISTRY-}shoppingcartservice
    build:
      context: ./src/ShoppingCartService
      dockerfile: Dockerfile
    depends_on:
      - configserver
      - eurekaserver
      - mysql
  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: ./src/OrderService
      dockerfile: Dockerfile
    depends_on:
      - configserver
      - eurekaserver
      - mysql
  musicstore:
    image: ${DOCKER_REGISTRY-}musicstore
    build:
      context: ./src/MusicStoreUI
      dockerfile: Dockerfile
    depends_on:
      - configserver
      - eurekaserver
      - musicservice
      - shoppingcartservice
      - orderservice
      - mysql
