name: musicstore
services:
- name: musicstoreservice
  project: src/MusicStoreService/MusicStoreService.csproj
- name: musicstoreui
  project: src/MusicStoreUI/MusicStoreUI.csproj
- name: orderservice
  project: src/OrderService/OrderService.csproj
- name: shoppingcartservice
  project: src/ShoppingCartService/ShoppingCartService.csproj

- name: config-server
  image: steeltoeoss/configserver:1.3.2
  volumes:
    - source: ./src/config
    - target: /config
  bindings:
    - containerPort: 8888
      protocol: http
  
- name: eureka
  image: steeltoeoss/eurekaserver:1.4.4
  bindings:
    - containerPort: 8761  
      protocol: http

- name: mysql
  image: mysql:5.7
  bindings:
    - containerPort: 3306
      protocol: http
  env:
    - name: MYSQL_ROOT_PASSWORD
      value: steeltoe
    - name: MYSQL_DATABASE
      value: steeltoe
    - name: MYSQL_USER
      value: steeltoe
    - name: MYSQL_PASSWORD
      value: steeltoe