AppSettings:
  SiteTitle: Music Store
  CacheDbResults: true
Logging: 
  IncludeScopes: true
  LogLevel: 
    Default: Information
    System: Warning
    Microsoft: Warning
    Steeltoe.Discovery: Debug
    Steeltoe.Management.Endpoint: Information

eureka:
  client:
    serviceUrl: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
mysql:
  client:
    server: mysql
    sslmode: none
redis:
  client:
    host: redis
management:
  endpoints:
    actuator:
      exposure:
        include: [ "*" ]
spring:
  boot:
    admin:
      client:
        url: http://bootadmin:1111
