AppSettings:
  SiteTitle: Music Store
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information

eureka:
  client:
    serviceUrl: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
mysql:
  client:
    server: mysql
    sslmode: none
redis:
  client:
    host: redis
management:
  endpoints:
    actuator:
      exposure:
        include: [ "*" ]
