eureka:
  client:
    shouldRegisterWithEureka: false
mysql:
  client:
    database: store
    username: root
    password: steeltoe
redis:
  client:
    host: redis
DefaultAdminUsername: Administrator@test.com
DefaultAdminPassword: YouShouldChangeThisPassword1!
spring:
  boot:
    admin:
      client:
        basePath: https://musicstoreui/