eureka:
  client:
    shouldFetchRegistry: false
mysql:
  client:
    database: steeltoe
    username: root
    password: steeltoe
postgres:
  client:
    database: steeltoe
    username: steeltoe
    password: steeltoe