eureka:
  client:
    shouldFetchRegistry: false
mysql:
  client:
    database: cart
    username: root
    password: steeltoe
spring:
  boot:
    admin:
      client:
        basePath: http://shoppingcartservice/