eureka:
  client:
    shouldFetchRegistry: false
mysql:
  client:
    database: steeltoe1
    username: root
    password: steeltoe
postgres:
  client:
    database: steeltoe1
    username: steeltoe
    password: steeltoe